name: Build macOS .app

on:
  push:
    branches: [ main ]  # o la rama que uses
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel py2app

      - name: Build .app with py2app
        run: python3 bloqueador_auto_mac/setup.py py2app

      - name: Upload .app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nomore_mac.app
          path: bloqueador_auto_mac/dist/nomore_mac.app
